branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

install:
  - "pip install numpy nibabel>=2.2 six nose coverage"

script:
  - nosetests --with-coverage --cover-package=cifti --where=cifti
