branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

install:
  - "pip install numpy nibabel>=2.2 six pytest pytest-runner coverage"

script:
  - pytest --cov=cifti
